name: Compatibility Test

on:
  workflow_dispatch:
    inputs:
      image_1:
        description: "The image to use for Keycloak instance 1"
        type: string
        default: "quay.io/keycloak/keycloak:nightly"
      image_2:
        description: "The image to use for Keycloak instance 2"
        type: string
        default: "quay.io/keycloak/keycloak:nightly"

jobs:
  compatibility-test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Keycloak main repository
        uses: actions/checkout@v6
        with:
          repository: 'keycloak/keycloak'
          ref: "main"

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Testing
        shell: bash
        run: |
          ./mvnw install dependency:resolve -B -V -e -DskipTests -DskipExamples -DexcludeGroupIds=org.keycloak -Dsilent=true
          ./mvnw package -B -pl quarkus/server/,quarkus/dist/
          ./mvnw verify -B -pl tests/clustering
        env:
          KC_TEST_SERVER_IMAGES: "${{ inputs.image_1 }},${{ inputs.image_2 }}"
